### ISSUE TITLE
[RFE] please add --html output directly to csdiff

### ISSUE THREAD

**Issue by fabbione** [kdudka/csdiff#13]
Hi Kamil,

would you please consider to add such option directly inside csdiff and skip a step to go through cshtml?

it would be pretty much feature equivalent to `cov-format-errors --dir=./cov --html-output cov.html` without using another command.

Thanks
Fabio

**Comment by kdudka** [comment]
Hi Fabio,

thanks for the proposal!

I am not sure whether this is the way to go.  If we added this option to csdiff, it would still be missing in csgrep and cssort.  Sooner or later the interface would be more complex than necessary.

I would prefer if each of the utilities had one well-defined responsibility and more complex tasks were implemented by chaining the utilities with each other.  For example:
```sh
$ cov-format-errors --dir=./cov --json-output-v7 /dev/stdout \
    | csgrep --mode=json --remove-duplicates \
    | csdiff ./old-results.js - \
    | cshtml - \
    > ./added-potential-bugs.html
```

**Comment by fabbione** [comment]
@kdudka sure understood. I was just looking for "hopefully" simple feature parity with cov-format-errors and avoid jumping around. Hardly a critical issue :)

thanks for coming back to me so quickly.

Fabio

**Comment by kdudka** [comment]
I should have looked at the list of currently supported options of csdiff first.  We already have `--coverity-output` and `--json-output` there.  So introducing `csdiff --html-output` actually makes sense.

**Comment by kdudka** [comment]
I have opened a pull request to implement this: https://github.com/kdudka/csdiff/pull/14

**Comment by fabbione** [comment]
@kdudka one "odd" question related to the html output, and this might very well be another request in itself. Is it possible to preserve the html output format from coverity itself?

Comparing the full output from coverity https://kronosnet.org/blabla/ vs htm´ified version of csdiff https://kronosnet.org/bla/ the full output is easier to parse for new comers I think. Anything we could do about it?

Thanks
Fabio

**Comment by kdudka** [comment]
csdiff never inputs HTML.  Obviously the format is intended for humans, not for further processing of the data.  What I believe would help to some extent is the `--embed-context` option of csgrep.  It embeds the given number of context lines from the source code into each report.

**Comment by fabbione** [comment]
Sorry I didn´t express myself correctly. I understand that csdiff doesn´t take HTML in input and HTML is final. can we make the output of cshtml looks like the output of cov --html ?

**Comment by kdudka** [comment]
The JSON output produced by `cov-format-errors` does not contain any source code.  So we would need to go through the reports in the JSON output and pick the actual source code directly from the source tree, assuming that the source tree is still available.  This is how `csgrep --embed-context` works today.  The related source code files are contained in Coverity's intermediate directory, too, but the data format is undocumented and is not supposed be used for anything but Coverity itself.  Extending tools that are not open source is difficult.

**Comment by kdudka** [comment]
Needless to say that this approach does not work well for files that are removed, overwritten, or recreated during the build.  In that case we might pick source code completely unrelated to the source code actually processed by the static analyzer.

**Comment by fabbione** [comment]
@kdudka got it and thanks for the explanation.
