### ISSUE TITLE
count duplicate reports per file and better inform about them

### ISSUE THREAD

**Issue by praiskup** [kdudka/csdiff#6]
Consider this situation:
```diff
diff --git a/test.py b/test.py
index 60b7683..b350521 100644
--- a/test.py
+++ b/test.py
@@ -5,5 +5,8 @@ for the pylint testing
 class _AClass:
     i = 10
 
+class _BClass:
+    i = 15
+
 class _CClass:
     i = 
```

The ouput from `csdiff old.log new.log` is:
```
Error: PROSPECTOR_WARNING:
/test.py:11: R0903[pylint]: Too few public methods (0/2)
```

This will be likely seen as false positive if printed without any other
context (which is the case in our CI, we don't want to bother people with
old issues).

It would be nice to say something like this instead:
```
# The very same report was present N times in old list of defects, and is
# present M times in the new list of defects.  We print only one random
# occurrence of this report, so note that the newly added defect(s) are
# likely on different line then we report here.
Error: PROSPECTOR_WARNING:
/test.py:11: R0903[pylint]: Too few public methods (0/2)
```

**Comment by kdudka** [comment]
I completely agree that such output is misleading.  On the other hand, I am not convinced that prepending the report with a comment would significantly improve the situation.  Would not it be better to improve pylint such that it includes name of the class in the diagnostic message?  I believe that users of pylint would take advantage of it even in case there was a single occurrence of the report.

**Comment by praiskup** [comment]
Yeah, definitely... but it's long shot, and I'm sure this isn't only pylint problem, or is it?

**Comment by praiskup** [comment]
If only pylint is in such a bad shape, let's scratch this idea.  I thought that this
feature would be generally useful (at least opt-in).  Feel free to WONTFIX this.
I'll try to open issues against pylint, and perhaps blacklist those chackers to
not pollute the output too much...

**Comment by kdudka** [comment]
Counterexamples could be created for sure.  But I do not remember any users complaining about such reports coming from Covscan's differential scans, which we automatically trigger for all minor RHEL updates.  I believe it is caused by the fact that Pylint is disabled by default in Covscan.

**Comment by praiskup** [comment]
We have to put `{obj}` into the `--msg-format` to make csdiff happy.  So I don't
need this feature anyway.
