### ISSUE TITLE
csdiff doesn't parse it's `-c` output

### ISSUE THREAD

**Issue by praiskup** [kdudka/csdiff#7]
Reproducible with json test files in this repo:
```
11:06:47 ~/rh/projects/csdiff$ ./csdiff_build/csdiff -c ./tests/diff-misc/11-pylint-copr-json-new.err ./tests/diff-misc/11-pylint-copr-json-old.err > fixed.err
11:06:57 ~/rh/projects/csdiff$ cp fixed.err added.err 
11:07:09 ~/rh/projects/csdiff$ ./csdiff_build/csdiff fixed.err added.err
fixed.err:2: parse error: wrong token: T_UNKNOWN (expected T_EVENT)
fixed.err:4: parse error: wrong token: T_CHECKER (expected T_EVENT)
fixed.err:5: parse error: wrong token: T_UNKNOWN (expected T_EVENT)
fixed.err:5: parse error: wrong token: T_UNKNOWN (expected T_EVENT)
fixed.err:7: parse error: wrong token: T_CHECKER (expected T_EVENT)
fixed.err:8: parse error: wrong token: T_UNKNOWN (expected T_EVENT)
fixed.err:8: parse error: wrong token: T_UNKNOWN (expected T_EVENT)
fixed.err:9: parse error: wrong token: T_UNKNOWN (expected T_EVENT)
fixed.err:10: parse error: wrong token: T_UNKNOWN (expected T_EVENT)
fixed.err:10: parse error: wrong token: T_NULL (expected T_EVENT)
fixed.err:10: parse error: failed to guess key event
added.err:2: parse error: wrong token: T_UNKNOWN (expected T_EVENT)
added.err:4: parse error: wrong token: T_CHECKER (expected T_EVENT)
added.err:5: parse error: wrong token: T_UNKNOWN (expected T_EVENT)
added.err:5: parse error: wrong token: T_UNKNOWN (expected T_EVENT)
added.err:7: parse error: wrong token: T_CHECKER (expected T_EVENT)
added.err:8: parse error: wrong token: T_UNKNOWN (expected T_EVENT)
added.err:8: parse error: wrong token: T_UNKNOWN (expected T_EVENT)
added.err:9: parse error: wrong token: T_UNKNOWN (expected T_EVENT)
added.err:10: parse error: wrong token: T_UNKNOWN (expected T_EVENT)
added.err:10: parse error: wrong token: T_NULL (expected T_EVENT)
added.err:10: parse error: failed to guess key event
```

**Comment by kdudka** [comment]
Thank you for reporting it!  This is because the event format does not match any format we know of yet, neither with GCC parser, nor with Coverity/emacs-style parser:

https://github.com/kdudka/csdiff/blob/5a3e60c9/gcc-parser.cc#L66
https://github.com/kdudka/csdiff/blob/5a3e60c9/csparser.cc#L110

I see it is generated in your code: `"event": "{}({})".format(defect["message-id"], defect["symbol"])`.  Is it something that is already used elsewhere?  If not, would it be possible for example to use square brackets instead of circle ones?  That would be closer to the format that we already use for Prospector and Cppcheck.

**Comment by praiskup** [comment]
> would it be possible for example to use square brackets instead of circle ones

Sure.  This anyways doesn't affect me/us, so please close the issue if it doesn't
make sense to resolve.

**Comment by kdudka** [comment]
This certainly makes sense to resolve.  The question is how to resolve it properly.  The purpose of the plain-text format is to be further processable by other tools like editors and IDEs.  The format is not based on any formal specification.  We are developing it on the fly.  That is why I asked whether the event format containing circle brackets is already used by some pre-existing solutions.  If yes, we should make the parser in csdiff accept them.  If not, we could for example make the writer in csdiff emit a warning while writing events in a format that cannot be parsed later on.

**Comment by praiskup** [comment]
> That is why I asked whether the event format containing circle brackets is already used by some pre-existing solutions.

That was just made-up, in believe that csdiff doesn't care (the json is parsed correctly).
I just didn't think about it too much.  I'll try to change the output once I have code in hand
again.

**Comment by praiskup** [comment]
copr PR https://pagure.io/copr/copr/pull-request/1375

**Comment by praiskup** [comment]
> Is it something that is already used elsewhere? If not, would it be possible for example to use square brackets instead of circle ones? 

Square brackets don't seem to help, though.  Try with the attached file
[fixed.log](https://github.com/kdudka/csdiff/files/4599095/fixed.log)

**Comment by kdudka** [comment]
Thanks for the update!  This is much closer.  PR #9 makes dashes in events also accepted to make it fully work.
